/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.ThuKho;

import domainmodels.ManHinh;
import iservices.IManHinhService;
import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.CheckTrungService;
import services.ManHinhService;
import utilities.ULHelper;

/**
 *
 * @author ADMIN
 */
public class JplManHinh extends javax.swing.JPanel {

    private final IManHinhService svcMH = new ManHinhService() {
    };
    List<ManHinh> lstMH = new ArrayList<>();
    DefaultTableModel modelManHinh = new DefaultTableModel();
    Date date = Date.valueOf(LocalDate.now());
    int index;

    public JplManHinh() {
        initComponents();
        modelManHinh = (DefaultTableModel) tblMH.getModel();
    }

    public void filltableMS() {
        try {
            modelManHinh.setRowCount(0);
            lstMH = svcMH.getAll();
            for (ManHinh a : lstMH) {
                modelManHinh.addRow(new Object[]{
                    a.getMa(), a.getDoPhanGiai(), a.getInch(), a.getNgayTao(), a.getNgaySua(), a.getStatus(a.getTrangThai())
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void showdetailMS(int index) {
        try {
            txtMa4.setText(lstMH.get(index).getMa());
            txtDPG.setText(lstMH.get(index).getDoPhanGiai());
            if (lstMH.get(index).getTrangThai() == 0) {
                radCon4.setSelected(true);
            } else {
                if (lstMH.get(index).getTrangThai() == 1) {
                    radHet4.setSelected(true);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgMH = new javax.swing.ButtonGroup();
        pnlMH = new javax.swing.JPanel();
        pnlMHinfo = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        radCon4 = new javax.swing.JRadioButton();
        radHet4 = new javax.swing.JRadioButton();
        pnlMHbtn = new javax.swing.JPanel();
        btnAdd4 = new javax.swing.JButton();
        btnShow4 = new javax.swing.JButton();
        btnEdit4 = new javax.swing.JButton();
        btnDelete4 = new javax.swing.JButton();
        btnHide4 = new javax.swing.JButton();
        txtMa4 = new javax.swing.JTextField();
        txtDPG = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtInch = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblMH = new javax.swing.JTable();
        pnlMHsrc = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        txtName4 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        btnTang4 = new javax.swing.JButton();
        btnGiam4 = new javax.swing.JButton();
        cboTrangThai4 = new javax.swing.JComboBox<>();
        jLabel63 = new javax.swing.JLabel();

        pnlMH.setBackground(new java.awt.Color(255, 230, 234));

        pnlMHinfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlMHinfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin màn hình", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel37.setText("Mã");

        jLabel42.setText("Độ phân giải");

        jLabel60.setText("Trạng thái");

        radCon4.setText("Còn hàng");
        radCon4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCon4ActionPerformed(evt);
            }
        });

        radHet4.setText("Hết hàng");

        btnAdd4.setBackground(new java.awt.Color(255, 51, 0));
        btnAdd4.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd4.setText("Thêm");
        btnAdd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd4ActionPerformed(evt);
            }
        });

        btnShow4.setBackground(new java.awt.Color(255, 51, 0));
        btnShow4.setForeground(new java.awt.Color(255, 255, 255));
        btnShow4.setText("Hiện");
        btnShow4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShow4ActionPerformed(evt);
            }
        });

        btnEdit4.setBackground(new java.awt.Color(255, 51, 0));
        btnEdit4.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit4.setText("Sửa");
        btnEdit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit4ActionPerformed(evt);
            }
        });

        btnDelete4.setBackground(new java.awt.Color(255, 51, 0));
        btnDelete4.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete4.setText("Xóa");
        btnDelete4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete4ActionPerformed(evt);
            }
        });

        btnHide4.setBackground(new java.awt.Color(255, 51, 0));
        btnHide4.setForeground(new java.awt.Color(255, 255, 255));
        btnHide4.setText("Ẩn");
        btnHide4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHide4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMHbtnLayout = new javax.swing.GroupLayout(pnlMHbtn);
        pnlMHbtn.setLayout(pnlMHbtnLayout);
        pnlMHbtnLayout.setHorizontalGroup(
            pnlMHbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMHbtnLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlMHbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHide4)
                    .addComponent(btnDelete4)
                    .addComponent(btnEdit4)
                    .addComponent(btnShow4)
                    .addComponent(btnAdd4))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnlMHbtnLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd4, btnDelete4, btnEdit4, btnHide4, btnShow4});

        pnlMHbtnLayout.setVerticalGroup(
            pnlMHbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMHbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnShow4)
                .addGap(18, 18, 18)
                .addComponent(btnHide4)
                .addGap(18, 18, 18)
                .addComponent(btnAdd4)
                .addGap(18, 18, 18)
                .addComponent(btnEdit4)
                .addGap(18, 18, 18)
                .addComponent(btnDelete4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMHbtnLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdd4, btnDelete4, btnEdit4, btnHide4, btnShow4});

        txtDPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDPGActionPerformed(evt);
            }
        });

        jLabel1.setText("Inch");

        txtInch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMHinfoLayout = new javax.swing.GroupLayout(pnlMHinfo);
        pnlMHinfo.setLayout(pnlMHinfoLayout);
        pnlMHinfoLayout.setHorizontalGroup(
            pnlMHinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMHinfoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlMHinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel42)
                    .addComponent(jLabel60)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(pnlMHinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMa4, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDPG, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMHinfoLayout.createSequentialGroup()
                        .addComponent(radCon4)
                        .addGap(18, 18, 18)
                        .addComponent(radHet4))
                    .addComponent(txtInch, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlMHbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        pnlMHinfoLayout.setVerticalGroup(
            pnlMHinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMHinfoLayout.createSequentialGroup()
                .addGroup(pnlMHinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMHinfoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnlMHinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(txtMa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMHinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(txtDPG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMHinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtInch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMHinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radCon4)
                            .addComponent(radHet4)
                            .addComponent(jLabel60)))
                    .addGroup(pnlMHinfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlMHbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        tblMH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Ngày tạo", "Ngày sửa", "Trạnng thái"
            }
        ));
        tblMH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMHMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tblMH);

        pnlMHsrc.setBackground(new java.awt.Color(255, 255, 255));

        jLabel61.setText("Tra cứu tên:");

        jLabel62.setText("Sắp xếp theo tên");

        btnTang4.setText("Tăng");

        btnGiam4.setText("Giảm");

        jLabel63.setText("Trạng thái:");

        javax.swing.GroupLayout pnlMHsrcLayout = new javax.swing.GroupLayout(pnlMHsrc);
        pnlMHsrc.setLayout(pnlMHsrcLayout);
        pnlMHsrcLayout.setHorizontalGroup(
            pnlMHsrcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMHsrcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMHsrcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel62)
                    .addComponent(jLabel61)
                    .addComponent(jLabel63))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMHsrcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlMHsrcLayout.createSequentialGroup()
                        .addComponent(btnTang4)
                        .addGap(18, 18, 18)
                        .addComponent(btnGiam4))
                    .addComponent(cboTrangThai4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName4))
                .addGap(110, 110, 110))
        );
        pnlMHsrcLayout.setVerticalGroup(
            pnlMHsrcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMHsrcLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlMHsrcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel61))
                .addGap(18, 18, 18)
                .addGroup(pnlMHsrcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTrangThai4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63))
                .addGap(18, 18, 18)
                .addGroup(pnlMHsrcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTang4)
                    .addComponent(jLabel62)
                    .addComponent(btnGiam4))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMHLayout = new javax.swing.GroupLayout(pnlMH);
        pnlMH.setLayout(pnlMHLayout);
        pnlMHLayout.setHorizontalGroup(
            pnlMHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMHLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlMHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlMHinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMHLayout.createSequentialGroup()
                        .addComponent(jScrollPane9)
                        .addGap(18, 18, 18)
                        .addComponent(pnlMHsrc, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        pnlMHLayout.setVerticalGroup(
            pnlMHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMHinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(pnlMHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlMHsrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1077, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radCon4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCon4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radCon4ActionPerformed

    private void btnAdd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd4ActionPerformed
        // TODO add your handling code here:
        try {
            if (ULHelper.checknull(txtMa4, "Không được để mã trống!")) {
                return;
            } else {
                int trungMa = CheckTrungService.checkTrung(txtMa4.getText(),
                        "manhinh", "ma");
                if (trungMa != -1) {
                    JOptionPane.showMessageDialog(this, "Mã đã tồn tại!");
                    return;
                }
            }

            if (ULHelper.checknull(txtDPG, "Không được để tên trống!")) {
                return;
            }
            int stt = (radHet4.isSelected() ? 1 : 0);
            ManHinh mau = new ManHinh(txtMa4.getText(), txtDPG.getText(), Double.parseDouble(txtDPG.getText()), date, date, stt);
            int thongBao = svcMH.them(mau);
            if (thongBao == 1) {
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                filltableMS();
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại!");
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAdd4ActionPerformed

    private void btnShow4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShow4ActionPerformed
        // TODO add your handling code here:
        try {
            filltableMS();
            showdetailMS(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnShow4ActionPerformed

    private void btnEdit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit4ActionPerformed
        // TODO add your handling code here:
        try {
            if (ULHelper.checknull(txtMa4, "Không được để mã trống!")) {
                return;
            }

            if (ULHelper.checknull(txtDPG, "Không được để tên trống!")) {
                return;
            }
            lstMH = svcMH.getAll();

            Date tao = lstMH.get(index).getNgayTao();
            int stt = (radHet4.isSelected() ? 1 : 0);
            ManHinh mau = new ManHinh(txtMa4.getText(), txtDPG.getText(), Double.parseDouble(txtDPG.getText()), tao, date, stt);
            int thongBao = svcMH.sua(mau);
            if (thongBao == 1) {
                JOptionPane.showMessageDialog(this, "Sửa thành công!");
                filltableMS();
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thất bại!");
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEdit4ActionPerformed

    private void btnDelete4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete4ActionPerformed
        // TODO add your handling code here:
        try {
            String ma = txtMa4.getText();
            int thongBao = svcMH.xoa(ma);
            if (thongBao == 1) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                filltableMS();
                showdetailMS(0);
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDelete4ActionPerformed

    private void btnHide4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHide4ActionPerformed
        // TODO add your handling code here:
        try {
            modelManHinh.setRowCount(0);
            txtMa4.setText("");
            txtDPG.setText("");
            radCon4.setSelected(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnHide4ActionPerformed

    private void txtDPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDPGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDPGActionPerformed

    private void tblMHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMHMouseClicked
        // TODO add your handling code here:
        try {
            int index = tblMH.getSelectedRow();
            showdetailMS(index);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblMHMouseClicked

    private void txtInchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgMH;
    private javax.swing.JButton btnAdd4;
    private javax.swing.JButton btnDelete4;
    private javax.swing.JButton btnEdit4;
    private javax.swing.JButton btnGiam4;
    private javax.swing.JButton btnHide4;
    private javax.swing.JButton btnShow4;
    private javax.swing.JButton btnTang4;
    private javax.swing.JComboBox<String> cboTrangThai4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel pnlMH;
    private javax.swing.JPanel pnlMHbtn;
    private javax.swing.JPanel pnlMHinfo;
    private javax.swing.JPanel pnlMHsrc;
    private javax.swing.JRadioButton radCon4;
    private javax.swing.JRadioButton radHet4;
    private javax.swing.JTable tblMH;
    private javax.swing.JTextField txtDPG;
    private javax.swing.JTextField txtInch;
    private javax.swing.JTextField txtMa4;
    private javax.swing.JTextField txtName4;
    // End of variables declaration//GEN-END:variables
}
