/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Quanly;

import domainmodels.NhanVien;
import iservices.IChucVuService;
import iservices.INhanVienService;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.ChucVuService;
import services.NhanVienService;

public class JplNhanVien extends javax.swing.JPanel {

    private INhanVienService iNhanVienSV = new NhanVienService();
    private IChucVuService iChucVuSV = new ChucVuService();
    DefaultTableModel moDel = new DefaultTableModel();
    DefaultComboBoxModel comboxmodel = new DefaultComboBoxModel();

    public JplNhanVien() {
        initComponents();

        loadDataNhanVienDanglam(iNhanVienSV.getAllDangLam());
        loadDataNhanVienDaNghi(iNhanVienSV.getAllDaNghi());

        loadCombox(iNhanVienSV.getTenChucVu());
    }

    private void loadCombox(List<String> list) {
        comboxmodel = (DefaultComboBoxModel) cboChucVu.getModel();
        for (String string : list) {
            comboxmodel.addElement(string);
        }
    }

    private void loadDataNhanVienDanglam(List<NhanVien> listl) {
        moDel = (DefaultTableModel) tblNhanVienDangLam.getModel();
        moDel.setRowCount(0);
        for (NhanVien nhanVien : listl) {
            moDel.addRow(new Object[]{
                nhanVien.getMa(),
                nhanVien.getHo(),
                nhanVien.getTenDem(),
                nhanVien.getTen(),
                nhanVien.getGioiTinh(),
                nhanVien.getNgaySinh(),
                nhanVien.getEmail(),
                nhanVien.getSdt(),
                nhanVien.getDiaChi(),
                nhanVien.getIdCV(),
                nhanVien.getMatKhau(),
                nhanVien.getNgayTao(),
                nhanVien.getNgaySua(),
                nhanVien.getTrangThaiString()
            });
        }
    }

    private void loadDataNhanVienDaNghi(List<NhanVien> listl) {
        moDel = (DefaultTableModel) tblNhanVienDaNghi.getModel();
        moDel.setRowCount(0);
        for (NhanVien nhanVien : listl) {
            moDel.addRow(new Object[]{
                nhanVien.getMa(),
                nhanVien.getHo(),
                nhanVien.getTenDem(),
                nhanVien.getTen(),
                nhanVien.getGioiTinh(),
                nhanVien.getNgaySinh(),
                nhanVien.getEmail(),
                nhanVien.getSdt(),
                nhanVien.getDiaChi(),
                nhanVien.getIdCV(),
                nhanVien.getMatKhau(),
                nhanVien.getNgayTao(),
                nhanVien.getNgaySua(),
                nhanVien.getTrangThaiString()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        rdoDangLam = new javax.swing.JRadioButton();
        rdoDaNghi = new javax.swing.JRadioButton();
        jPanel12 = new javax.swing.JPanel();
        btnthem = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtTenDem = new javax.swing.JTextField();
        txtHo = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboChucVu = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        cboGioiTinh = new javax.swing.JComboBox<>();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel40 = new javax.swing.JLabel();
        btnza = new javax.swing.JButton();
        btnaz = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        txtTimten = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        cboLocChucVu = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhanVienDangLam = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNhanVienDaNghi = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(255, 230, 234));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel27.setText("Mã");

        jLabel28.setText("Tên");

        jLabel29.setText("Tên đệm");

        jLabel30.setText("Họ");

        jLabel31.setText("Ngày sinh");

        jLabel32.setText("SDT");

        jLabel33.setText("Địa chỉ");

        jLabel35.setText("Mật khẩu");

        jLabel38.setText("Trạng thái");

        buttonGroup1.add(rdoDangLam);
        rdoDangLam.setSelected(true);
        rdoDangLam.setText("Đang làm việc");

        buttonGroup1.add(rdoDaNghi);
        rdoDaNghi.setText("Đã nghỉ");

        btnthem.setBackground(new java.awt.Color(255, 51, 0));
        btnthem.setForeground(new java.awt.Color(255, 255, 255));
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnMoi.setBackground(new java.awt.Color(255, 51, 0));
        btnMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 51, 0));
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 51, 0));
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnMoi)
                    .addComponent(btnthem))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel12Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMoi, btnSua, btnXoa, btnthem});

        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnMoi)
                .addGap(18, 18, 18)
                .addComponent(btnthem)
                .addGap(12, 12, 12)
                .addComponent(btnSua)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel12Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMoi, btnSua, btnXoa, btnthem});

        jLabel2.setText("Chức vụ");

        jLabel7.setText("Giới tính");

        jLabel34.setText("Email");

        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel30))
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtHo)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTenDem, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDiaChi))
                                    .addComponent(jLabel29))))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel28)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboChucVu, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTen, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addComponent(rdoDangLam, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoDaNghi)))
                .addGap(47, 47, 47)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel27, jLabel28, jLabel29, jLabel30, jLabel31, jLabel32, jLabel33, jLabel35, jLabel38, jLabel7});

        jPanel11Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDiaChi, txtEmail, txtHo, txtMa, txtNgaySinh, txtSDT});

        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel35)
                                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel28)
                                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel31)))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenDem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel38)
                            .addComponent(rdoDangLam)
                            .addComponent(rdoDaNghi)
                            .addComponent(jLabel34)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel11Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboChucVu, jLabel2, jLabel27, jLabel28, jLabel29, jLabel30, jLabel31, jLabel32, jLabel33, jLabel35, jLabel38, jLabel7, txtDiaChi, txtEmail, txtHo, txtMa, txtMatKhau, txtNgaySinh, txtSDT, txtTen, txtTenDem});

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setText("Sắp xếp theo tên");

        btnza.setBackground(new java.awt.Color(255, 51, 51));
        btnza.setForeground(new java.awt.Color(255, 255, 255));
        btnza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-sort-alpha-up-20.png"))); // NOI18N
        btnza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnzaActionPerformed(evt);
            }
        });

        btnaz.setBackground(new java.awt.Color(255, 51, 51));
        btnaz.setForeground(new java.awt.Color(255, 255, 255));
        btnaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-sort-alpha-up-reversed-20.png"))); // NOI18N
        btnaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnazActionPerformed(evt);
            }
        });

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tra cứu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txtTimten.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimtenCaretUpdate(evt);
            }
        });
        txtTimten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTimtenMouseClicked(evt);
            }
        });
        txtTimten.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimtenKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimtenKeyReleased(evt);
            }
        });

        jLabel39.setText("Tên:");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel39)
                .addGap(18, 18, 18)
                .addComponent(txtTimten, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addContainerGap())
        );

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        cboLocChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thủ kho", "Nhân viên", "Quản lý" }));
        cboLocChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLocChucVuActionPerformed(evt);
            }
        });

        jLabel42.setText("Chức vụ");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel42)
                .addGap(30, 30, 30)
                .addComponent(cboLocChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboLocChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        tblNhanVienDangLam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblNhanVienDangLam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Họ", "Tên đệm", "Tên", "Giới tính", "Ngày sinh", "Email", "Sdt", "Địa chỉ", "Chức vụ", "Mật khẩu", "Ngày tạo", "Ngày sửa", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVienDangLam.setGridColor(new java.awt.Color(47, 85, 212));
        tblNhanVienDangLam.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblNhanVienDangLam.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblNhanVienDangLam.setShowGrid(true);
        tblNhanVienDangLam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienDangLamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNhanVienDangLam);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("ĐANG LÀM", jPanel1);

        tblNhanVienDaNghi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblNhanVienDaNghi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Họ", "Tên đệm", "Tên", "Giới tính", "Ngày sinh", "Email", "Sdt", "Địa chỉ", "Chức vụ", "Mật khẩu", "Ngày tạo", "Ngày sửa", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVienDaNghi.setGridColor(new java.awt.Color(47, 85, 212));
        tblNhanVienDaNghi.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblNhanVienDaNghi.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblNhanVienDaNghi.setShowGrid(true);
        tblNhanVienDaNghi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienDaNghiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblNhanVienDaNghi);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ĐÃ NGHỈ", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel40)
                        .addGap(18, 18, 18)
                        .addComponent(btnaz)
                        .addGap(18, 18, 18)
                        .addComponent(btnza)
                        .addGap(197, 197, 197))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnza, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel40)
                                .addComponent(btnaz, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        try {
            if (checkValidate()) {
                String ma = txtMa.getText();
                if (iNhanVienSV.checkTrungMa(ma) != null) {
                    JOptionPane.showMessageDialog(this, "Mã đã tồn tại, nhập mã khác");
                    return;
                }
                String ten = txtTen.getText();
                String tenDem = txtTenDem.getText();
                String ho = txtHo.getText();
                String gTinh = (String) cboGioiTinh.getSelectedItem();
                Date ngaySinh = (txtNgaySinh.getDate());
                String email = txtEmail.getText();
                String sdt = txtSDT.getText();
                String diachi = txtDiaChi.getText();
                String chucVu = iChucVuSV.getAll().get(cboChucVu.getSelectedIndex()).getId();
                String matKhau = txtMatKhau.getText();
                int trangThai;
                if (rdoDangLam.isSelected()) {
                    trangThai = 1;
                } else {
                    trangThai = 0;
                }

                NhanVien nhanVien = new NhanVien();
                nhanVien.setMa(ma);
                nhanVien.setTen(ten);
                nhanVien.setTenDem(tenDem);
                nhanVien.setHo(ho);
                nhanVien.setGioiTinh(gTinh);
                nhanVien.setNgaySinh(ngaySinh);
                nhanVien.setSdt(sdt);
                nhanVien.setDiaChi(diachi);
                nhanVien.setEmail(email);
                nhanVien.setIdCV(chucVu);
                nhanVien.setMatKhau(matKhau);
                nhanVien.setTrangThai(trangThai);
                iNhanVienSV.them(nhanVien);

                JOptionPane.showMessageDialog(this, "Thêm thành công");
                loadDataNhanVienDanglam(iNhanVienSV.getAllDangLam());
                loadDataNhanVienDaNghi(iNhanVienSV.getAllDaNghi());

                clearForm();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnthemActionPerformed
    private boolean checkValidate() {
        if (utilities.ULHelper.checknull(txtMa, "Không được để trống !")) {
            return false;
        }
        if (utilities.ULHelper.checknull(txtTen, "Không được để trống !")) {
            return false;
        }
        if (utilities.ULHelper.checknull(txtTenDem, "Không được để trống !")) {
            return false;
        }
        if (utilities.ULHelper.checknull(txtHo, "Không được để trống !")) {
            return false;
        }

        if (utilities.ULHelper.checknull(txtSDT, "Không được để trống !")) {
            return false;
        }

        if (utilities.ULHelper.CheckSDT(txtSDT, "Nhập số điện thoại đúng định dạng !")) {
            return false;
        }

        if (utilities.ULHelper.checknull(txtDiaChi, "Không được để trống !")) {
            return false;
        }
        if (utilities.ULHelper.checknull(txtMatKhau, "Không được để trống !")) {
            return false;
        }
        if (utilities.ULHelper.checknull(txtEmail, "Không được để trống !")) {
            return false;
        }
        if (utilities.ULHelper.checkEmail(txtEmail, "Nhập đúng định dạng !")) {
            return false;
        }
        return true;
    }
    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed
    private void clearForm() {
        txtMa.setText("");
        txtTen.setText("");
        txtTenDem.setText("");
        txtHo.setText("");
        cboGioiTinh.setSelectedIndex(0);
        txtNgaySinh.setDate(null);
        txtSDT.setText("");
        txtDiaChi.setText("");
        txtEmail.setText("");
        txtMatKhau.setText("");
        cboChucVu.setSelectedIndex(0);
        rdoDangLam.setSelected(true);
        tblNhanVienDangLam.clearSelection();
        tblNhanVienDaNghi.clearSelection();
        loadDataNhanVienDanglam(iNhanVienSV.getAllDangLam());
        loadDataNhanVienDaNghi(iNhanVienSV.getAllDaNghi());

    }
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        try {
            if (checkValidate()) {
                String ma = txtMa.getText();
                String ten = txtTen.getText();
                String tenDem = txtTenDem.getText();
                String ho = txtHo.getText();
                String gTinh = (String) cboGioiTinh.getSelectedItem();
                Date ngaySinh = txtNgaySinh.getDate();
                String sdt = txtSDT.getText();
                String diachi = txtDiaChi.getText();
                String email = txtEmail.getText();
                String chucVu = iChucVuSV.getAll().get(cboChucVu.getSelectedIndex()).getId();
                String matKhau = txtMatKhau.getText();
                int trangThai;
                if (rdoDangLam.isSelected()) {
                    trangThai = 1;
                } else {
                    trangThai = 0;
                }
                NhanVien nhanVien = new NhanVien();
                nhanVien.setMa(ma);
                nhanVien.setTen(ten);
                nhanVien.setTenDem(tenDem);
                nhanVien.setHo(ho);
                nhanVien.setGioiTinh(gTinh);
                nhanVien.setNgaySinh(ngaySinh);
                nhanVien.setSdt(sdt);
                nhanVien.setDiaChi(diachi);
                nhanVien.setEmail(email);
                nhanVien.setIdCV(chucVu);
                nhanVien.setMatKhau(matKhau);
                nhanVien.setTrangThai(trangThai);
                iNhanVienSV.sua(nhanVien);
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                loadDataNhanVienDanglam(iNhanVienSV.getAllDangLam());
                loadDataNhanVienDaNghi(iNhanVienSV.getAllDaNghi());
                clearForm();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (iNhanVienSV.getAll().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không còn gì để xoá");
            return;
        }
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá không ?");
        if (hoi != JOptionPane.YES_OPTION) {
            clearForm();
            return;
        } else {
            String ma = txtMa.getText();
            iNhanVienSV.xoa(ma);
            JOptionPane.showMessageDialog(this, "Xoá thành công");
            clearForm();
            loadDataNhanVienDanglam(iNhanVienSV.getAllDangLam());
            loadDataNhanVienDaNghi(iNhanVienSV.getAllDaNghi());
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTimtenCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimtenCaretUpdate

    }//GEN-LAST:event_txtTimtenCaretUpdate

    private void btnzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnzaActionPerformed
        List<NhanVien> list1 = iNhanVienSV.sapXepTenGiamNVLam();
        loadDataNhanVienDanglam(list1);
        List<NhanVien> list2 = iNhanVienSV.sapXepTenGiamNVNghi();
        loadDataNhanVienDaNghi(list2);
        JOptionPane.showMessageDialog(this, "Sắp xếp theo tên Z-A");
    }//GEN-LAST:event_btnzaActionPerformed

    private void btnazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnazActionPerformed
        List<NhanVien> list1 = iNhanVienSV.sapXepTenTangNVLam();
        loadDataNhanVienDanglam(list1);
        List<NhanVien> list2 = iNhanVienSV.sapXepTenTangNVNghi();
        loadDataNhanVienDaNghi(list2);
        JOptionPane.showMessageDialog(this, "Sắp xếp theo tên A-Z");
    }//GEN-LAST:event_btnazActionPerformed

    private void cboLocChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLocChucVuActionPerformed
        if (cboLocChucVu.getSelectedIndex() == -1) {
            List<NhanVien> list1 = iNhanVienSV.getAllDaNghi();
            List<NhanVien> list2 = iNhanVienSV.getAllDangLam();
            loadDataNhanVienDanglam(list2);
            loadDataNhanVienDaNghi(list1);
            return;
        } else {
            String chucVu = null;
            if (cboLocChucVu.getSelectedItem().toString().equals("Nhân viên")) {
                chucVu = "Nhân viên";
                List<NhanVien> list1 = iNhanVienSV.locChucVuNVLam(chucVu);
                List<NhanVien> list2 = iNhanVienSV.locChucVuNVNghi(chucVu);
                loadDataNhanVienDanglam(list1);
                loadDataNhanVienDaNghi(list2);
            } else if (cboLocChucVu.getSelectedItem().toString().equals("Quản lý")) {
                chucVu = "Quản lý";
                List<NhanVien> list1 = iNhanVienSV.locChucVuNVLam(chucVu);
                List<NhanVien> list2 = iNhanVienSV.locChucVuNVNghi(chucVu);
                loadDataNhanVienDanglam(list1);
                loadDataNhanVienDaNghi(list2);
            } else if (cboLocChucVu.getSelectedItem().toString().equals("Thủ kho")) {
                chucVu = "Thủ kho";
                List<NhanVien> list1 = iNhanVienSV.locChucVuNVLam(chucVu);
                List<NhanVien> list2 = iNhanVienSV.locChucVuNVNghi(chucVu);
                loadDataNhanVienDanglam(list1);
                loadDataNhanVienDaNghi(list2);
            }
        }
    }//GEN-LAST:event_cboLocChucVuActionPerformed

    private void tblNhanVienDangLamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienDangLamMouseClicked
        int index = tblNhanVienDangLam.getSelectedRow();
        NhanVien nv = iNhanVienSV.getAllDangLam().get(index);
        txtMa.setText(tblNhanVienDangLam.getValueAt(index, 0).toString());
        txtHo.setText(tblNhanVienDangLam.getValueAt(index, 1).toString());
        txtTenDem.setText(tblNhanVienDangLam.getValueAt(index, 2).toString());
        txtTen.setText(tblNhanVienDangLam.getValueAt(index, 3).toString());
        cboGioiTinh.setSelectedItem(tblNhanVienDangLam.getValueAt(index, 4).toString());
        txtNgaySinh.setDate(nv.getNgaySinh());
        txtEmail.setText(tblNhanVienDangLam.getValueAt(index, 6).toString());
        txtSDT.setText(tblNhanVienDangLam.getValueAt(index, 7).toString());
        txtDiaChi.setText(tblNhanVienDangLam.getValueAt(index, 8).toString());
        cboChucVu.setSelectedItem(tblNhanVienDangLam.getValueAt(index, 9).toString());
        txtMatKhau.setText(tblNhanVienDangLam.getValueAt(index, 10).toString());
        if (tblNhanVienDangLam.getValueAt(index, 13).equals("Đang làm việc")) {
            rdoDangLam.setSelected(true);
        } else {
            rdoDaNghi.setSelected(true);
        }
    }//GEN-LAST:event_tblNhanVienDangLamMouseClicked

    private void tblNhanVienDaNghiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienDaNghiMouseClicked
        int index = tblNhanVienDaNghi.getSelectedRow();
        NhanVien nv = iNhanVienSV.getAllDaNghi().get(index);
        txtMa.setText(tblNhanVienDaNghi.getValueAt(index, 0).toString());
        txtHo.setText(tblNhanVienDaNghi.getValueAt(index, 1).toString());
        txtTenDem.setText(tblNhanVienDaNghi.getValueAt(index, 2).toString());
        txtTen.setText(tblNhanVienDaNghi.getValueAt(index, 3).toString());
        cboGioiTinh.setSelectedItem(tblNhanVienDaNghi.getValueAt(index, 4).toString());
        txtNgaySinh.setDate(nv.getNgaySinh());
        txtEmail.setText(tblNhanVienDaNghi.getValueAt(index, 6).toString());
        txtSDT.setText(tblNhanVienDaNghi.getValueAt(index, 7).toString());
        txtDiaChi.setText(tblNhanVienDaNghi.getValueAt(index, 8).toString());
        cboChucVu.setSelectedItem(tblNhanVienDaNghi.getValueAt(index, 9).toString());
        txtMatKhau.setText(tblNhanVienDaNghi.getValueAt(index, 10).toString());
        if (tblNhanVienDaNghi.getValueAt(index, 13).equals("Đang làm việc")) {
            rdoDangLam.setSelected(true);
        } else {
            rdoDaNghi.setSelected(true);
        }
    }//GEN-LAST:event_tblNhanVienDaNghiMouseClicked

    private void txtTimtenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimtenKeyReleased
        List<NhanVien> list1 = iNhanVienSV.timTenNvLam(txtTimten.getText().trim());
        loadDataNhanVienDanglam(list1);
        List<NhanVien> list2 = iNhanVienSV.timTenNvNghi(txtTimten.getText().trim());
        loadDataNhanVienDaNghi(list2);
    }//GEN-LAST:event_txtTimtenKeyReleased

    private void txtTimtenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimtenKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimtenKeyPressed

    private void txtTimtenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimtenMouseClicked
        cboLocChucVu.setSelectedIndex(0);
    }//GEN-LAST:event_txtTimtenMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnaz;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnza;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboChucVu;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private javax.swing.JComboBox<String> cboLocChucVu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rdoDaNghi;
    private javax.swing.JRadioButton rdoDangLam;
    private javax.swing.JTable tblNhanVienDaNghi;
    private javax.swing.JTable tblNhanVienDangLam;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMatKhau;
    private com.toedter.calendar.JDateChooser txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenDem;
    private javax.swing.JTextField txtTimten;
    // End of variables declaration//GEN-END:variables
}
